### ISSUE TITLE
error in calling m_cnem3d_scni 

### ISSUE THREAD

**Issue by matvin** [isolat/cnem#1]
I'm trying to run the SCNI call on MATLAB R2021a ( OS Big Sur  ) and running into the following error:

One or more output arguments not assigned during call to "cnem3d".

Error in m_cnem3d_scni (line 39)
cnem3d(0,XYZ_Noeud',IN_Tri_Ini',Type_Call_Tet,Type_FF,Sup_NN_GS);

I believe this may be related to some issue with MEX when running make_cnem3d. make_cnem3d runs without any errors however there are a lot of warnings of deprecated features related to TBB which I can't fix by running older versions of CNEM or TBB .

for example:

In file included from /Users/Gauchomatteochan/Desktop/Documents/MatTools/cnem-master/matlab/bin/../../src/CNEM3D/Global_Header.h:97:
../../tbb-2020.1/win/tbb/include/tbb/mutex.h:21:9: warning: TBB Warning: tbb/mutex.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual. [-W#pragma-messages]
#pragma message("TBB Warning: tbb/mutex.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.")
        ^
2 warnings generated.

In addition I do not see any .mat functions in the CNEM3D folder after running make_cnem3d. Does this mean that the source files were not properly compiled? The contents of the CNEM3D folder all remain .cpp and .h files as before running make_cnem3d.

Thank you so for your help!

Best,

Matteo

**Comment by isolat** [comment]
Hello Matteo, yes it is related to TBB, in mac OS system they declared the same names for mutex and other parallelization primitve as those declared in TBB, I have already solved the problem, I will send you the latest version ,
BrLounes 
    Le vendredi 23 avril 2021, 20:40:02 UTC+2, matvin ***@***.***> a écrit :  
 
 


I'm trying to run the SCNI call on MATLAB R2021a ( OS Big Sur ) and running into the following error:

One or more output arguments not assigned during call to "cnem3d".

Error in m_cnem3d_scni (line 39)
cnem3d(0,XYZ_Noeud',IN_Tri_Ini',Type_Call_Tet,Type_FF,Sup_NN_GS);

I believe this may be related to some issue with MEX when running make_cnem3d. make_cnem3d runs without any errors however there are a lot of warnings of deprecated features related to TBB which I can't fix by running older versions of CNEM or TBB .

for example:

In file included from /Users/Gauchomatteochan/Desktop/Documents/MatTools/cnem-master/matlab/bin/../../src/CNEM3D/Global_Header.h:97:
../../tbb-2020.1/win/tbb/include/tbb/mutex.h:21:9: warning: TBB Warning: tbb/mutex.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual. [-W#pragma-messages]
#pragma message("TBB Warning: tbb/mutex.h is deprecated. For details, please see Deprecated Features appendix in the TBB reference manual.")
^
2 warnings generated.

In addition I do not see any .mat functions in the CNEM3D folder after running make_cnem3d. Does this mean that the source files were not properly compiled? The contents of the CNEM3D folder all remain .cpp and .h files as before running make_cnem3d.

Thank you so for your help!

Best,

Matteo

**Comment by matvin** [comment]
Fantastic, and thank you so much for the quick reply!  Very excited to start working with your toolbox :)

**Comment by matvin** [comment]
If required my email is mlv16@ic.ac.uk


Thank you!

**Comment by isolat** [comment]
Hi again ! here is the latest version tested with the latest version of matlab, don't forget to compile the tet binary by running the makefile (libbuild / make_tet).Do not hesitate to contact me for any problem or question regarding the libraryBr
cnem_23_04_21.zip



    Le vendredi 23 avril 2021, 21:33:09 UTC+2, matvin ***@***.***> a écrit :  
 
 


If required my email is ***@***.***

Thank you!

**Comment by isolat** [comment]
Thank you so much for your help, have a great week!

Best,

Matteo


Matteo Vinao-Carl | PhD Student
Centre for Doctoral Training in Neurotechnology
Imperial College London
E315A Burlington Danes Building, DuCane Road, London W120NN  UK
Tel | +44 797 946 7275




________________________________

**Comment by isolat** [comment]
Dear Lounes,

Sorry to trouble you again with a basic question but I'm having trouble compiling the tet binary.
I see that make_tet unlike make_cnem3d is a text file and cannot be run from matlab.
I tried running it from the terminal in bash / zsh but it doesn't seem to be working.

Thank you again for your help!

Best,

Matteo


Matteo Vinao-Carl | PhD Student
Centre for Doctoral Training in Neurotechnology
Imperial College London
E315A Burlington Danes Building, DuCane Road, London W120NN  UK
Tel | +44 797 946 7275




________________________________

**Comment by isolat** [comment]
Hi Matteo, no problem, you don't trouble me at all,Yes it's a c++ binary not a matalab mex, so you can't build it on matlab.To generate tet binary, go to a bash /zsh, navigate to make_tet directory, and run :make - f make_tetkeep me informed,br
    Le lundi 26 avril 2021, 13:53:01 UTC+2, Vinao-Carl, Matteo L ***@***.***> a écrit :  
 
 Dear Lounes,
Sorry to trouble you again with a basic question but I'm having trouble compiling the tet binary. I see that make_tet unlike make_cnem3d is a text file and cannot be run from matlab.I tried running it from the terminal in bash / zsh but it doesn't seem to be working.
Thank you again for your help!
Best,
Matteo



Matteo Vinao-Carl |PhD Student Centre for Doctoral Training in NeurotechnologyImperial College LondonE315A Burlington Danes Building, DuCane Road, London W120NN  UKTel | +44 797 946 7275

**Comment by matvin** [comment]
Hi Lounes,

Thank you very much for your patience 

make -f make_tet 

This generates the following files:

tetgen.o
predicates.o 
main_tetgen_exe.o 

However it seems to stop after the following error:

ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [tet] Error 1

After this, I tried running make_cnem3d . I noticed that it seems to successfully create a large number of .o files in the libbuild folder. However these files are all immediately erased after MEX has finished, including the files generated from make -f make_tet

This is with an older version of TBB (2019) . When repeating with the latest version (2021) i now go back to the old problem which was these warnings / deprecation error for mutex.h and task_scheduler_init.h

**Comment by isolat** [comment]
aaah you haven't the 32bit system librarys, edit the make_tet and remove all -m32 (3 occurrence)
    Le lundi 26 avril 2021, 15:27:06 UTC+2, matvin ***@***.***> a écrit :  
 
 


Hi Lounes,

Thank you very much for your patience

make -f make_tet

This generates the following files:

tetgen.o
predicates.o
main_tetgen_exe.o

However it seems to stop after the following error:

ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [tet] Error 1

After this, I tried running make_cnem3d . I noticed that it seems to successfully create a large number of .o files in the libbuild folder. However these files are all immediately erased after MEX has finished, including the files generated from make -f make_tet

This is with an older version of TBB (2019) . When repeating with the latest version (2021) i now go back to the old problem which was these warnings / deprecation error for mutex.h and task_scheduler_init.h

**Comment by matvin** [comment]
It's all working!! Thank you!!!

**Comment by isolat** [comment]
👍
you're welcome

    Le lundi 26 avril 2021, 15:53:08 UTC+2, matvin ***@***.***> a écrit :  
 
 


It's all working!! Thank you!!!
